BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Loans CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Customers CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE Customers
(
    CustomerID NUMBER PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    DOB DATE NOT NULL,
    Balance NUMBER(12,2) DEFAULT 0 NOT NULL,
    IsVIP VARCHAR2(5) DEFAULT 'FALSE' NOT NULL,
    CONSTRAINT chk_customer_vip CHECK (IsVIP IN ('TRUE', 'FALSE'))
);

CREATE TABLE Loans
(
    LoanID NUMBER PRIMARY KEY,
    CustomerID NUMBER NOT NULL,
    InterestRate NUMBER(5,2) NOT NULL,
    DueDate DATE NOT NULL,

    CONSTRAINT fk_customer
    FOREIGN KEY(CustomerID)
    REFERENCES Customers(CustomerID)
);
